mautic:
  image: nhrd/mautic
  container_name: nhrd.mautic.app
  hostname: nhrd.mautic.app
  restart: always
  links:
    - mauticdb:mysql
  volumes:
    - ./volumes/media/files:/var/www/html/media/files
    - ./volumes/media/images:/var/www/html/media/images
  environment:
    - VIRTUAL_HOST=mkt.nhrd.co

mauticdb:
  image: mysql:5.6
  container_name: nhrd.mautic.db
  hostname: nhrd.mautic.db
  volumes:
     - ./volumes/db:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: XiNCSiuVqK34