mautic:
  image: nhrd/mautic
  container_name: iledepipa.mautic.app
  hostname: iledepipa.mautic.app
  restart: always
  links:
    - mauticdb:mysql
  volumes:
    - ./volumes/media/files:/var/www/html/media/files
    - ./volumes/media/images:/var/www/html/media/images
    # - ./volumes/app:/var/www/html/app
  environment:
    - VIRTUAL_HOST=mkt.iledepipa.com.br

mauticdb:
  image: mysql:5.6
  container_name: iledepipa.mautic.db
  hostname: iledepipa.mautic.db
  volumes:
     - ./volumes/db:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: NB54Cp6Vb92d